# Generated by Django 5.2.16 on 2026-07-15 06:30
# Tenant bigint PK → UUID: recreate empty `tenants` table (PG cannot cast bigint→uuid).

import uuid

from django.db import migrations, models


TENANT_UUID_SQL = """
-- Empty DB: drop old/new tenants table; CASCADE removes dependent FK constraints.
DROP TABLE IF EXISTS tenants_tenant CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

CREATE TABLE tenants (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    slug varchar(255) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX tenants_slug_like ON tenants (slug varchar_pattern_ops);

-- Empty child tables: convert FK columns without DROP/ADD COLUMN.
ALTER TABLE companies
    ALTER COLUMN tenant_id TYPE uuid USING NULL::uuid;
ALTER TABLE users
    ALTER COLUMN tenant_id TYPE uuid USING NULL::uuid;

-- dataruns may not exist yet on a fresh migrate (tenants.0002 has no dataruns dep).
DO $$
BEGIN
    IF to_regclass('public.dataruns_datarun') IS NOT NULL THEN
        ALTER TABLE dataruns_datarun
            ALTER COLUMN tenant_id TYPE uuid USING NULL::uuid;
    END IF;
END $$;

-- Let PostgreSQL name the constraints (no hardcoded Django hash names).
ALTER TABLE companies
    ADD FOREIGN KEY (tenant_id) REFERENCES tenants (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE users
    ADD FOREIGN KEY (tenant_id) REFERENCES tenants (id) DEFERRABLE INITIALLY DEFERRED;

DO $$
BEGIN
    IF to_regclass('public.dataruns_datarun') IS NOT NULL THEN
        ALTER TABLE dataruns_datarun
            ADD FOREIGN KEY (tenant_id) REFERENCES tenants (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""

TENANT_BIGINT_SQL = """
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS tenants_tenant CASCADE;

CREATE TABLE tenants_tenant (
    id bigserial PRIMARY KEY,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX tenants_tenant_slug_like ON tenants_tenant (slug varchar_pattern_ops);

ALTER TABLE companies
    ALTER COLUMN tenant_id TYPE bigint USING NULL::bigint;
ALTER TABLE users
    ALTER COLUMN tenant_id TYPE bigint USING NULL::bigint;

DO $$
BEGIN
    IF to_regclass('public.dataruns_datarun') IS NOT NULL THEN
        ALTER TABLE dataruns_datarun
            ALTER COLUMN tenant_id TYPE bigint USING NULL::bigint;
    END IF;
END $$;

ALTER TABLE companies
    ADD FOREIGN KEY (tenant_id) REFERENCES tenants_tenant (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE users
    ADD FOREIGN KEY (tenant_id) REFERENCES tenants_tenant (id) DEFERRABLE INITIALLY DEFERRED;

DO $$
BEGIN
    IF to_regclass('public.dataruns_datarun') IS NOT NULL THEN
        ALTER TABLE dataruns_datarun
            ADD FOREIGN KEY (tenant_id) REFERENCES tenants_tenant (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="connector",
            name="type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="connectorsnapshot",
            name="version",
            field=models.IntegerField(),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="tenant",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="tenant",
                    name="name",
                    field=models.TextField(),
                ),
                migrations.AlterModelTable(
                    name="tenant",
                    table="tenants",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=TENANT_UUID_SQL,
                    reverse_sql=TENANT_BIGINT_SQL,
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.TextField(
                choices=[
                    ("admin", "Admin"),
                    ("analyst", "Analyst"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
            ),
        ),
    ]
