# Generated by Django 5.2.16 on 2026-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_dbml_schema_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connector',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='connectorsnapshot',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=32),
        ),
    ]
