# Generated by Django 5.2.16 on 2026-07-15 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0002_initial'),
        ('tenants', '0002_dbml_schema_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFixBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('expected_revenue_impact', models.DecimalField(decimal_places=6, max_digits=20)),
                ('risk_reduction', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_fix_blueprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'lifecycle_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'scoring_models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFixAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.TextField()),
                ('target_entity', models.TextField()),
                ('target_id', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.TextField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dataruns.datafixblueprint')),
            ],
            options={
                'db_table': 'data_fix_actions',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.TextField(choices=[('full', 'Full'), ('incremental', 'Incremental')])),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tenants.company')),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QaCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.TextField()),
                ('result', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_checks', to='dataruns.run')),
            ],
            options={
                'db_table': 'qa_checks',
            },
        ),
        migrations.CreateModel(
            name='LifecycleProfileContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.TextField()),
                ('stage', models.TextField()),
                ('score', models.DecimalField(decimal_places=6, max_digits=20)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('lifecycle_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dataruns.lifecycleprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_profile_contacts', to='dataruns.run')),
            ],
            options={
                'db_table': 'lifecycle_profile_contacts',
            },
        ),
        migrations.AddField(
            model_name='lifecycleprofile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_profiles', to='dataruns.run'),
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='dataruns.run')),
            ],
            options={
                'db_table': 'handoffs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='datafixblueprint',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fix_blueprints', to='dataruns.run'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('performed_by', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='dataruns.run')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('approved_by', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='dataruns.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='dataruns.run')),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='RunConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_connectors', to='tenants.connectorsnapshot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_connectors', to='dataruns.run')),
            ],
            options={
                'db_table': 'run_connectors',
            },
        ),
        migrations.CreateModel(
            name='RunDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_run_id', models.UUIDField()),
                ('diff_summary', models.JSONField(blank=True, default=dict)),
                ('changes_count', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='dataruns.run')),
            ],
            options={
                'db_table': 'run_diff',
            },
        ),
        migrations.CreateModel(
            name='RunIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.TextField()),
                ('entity_id', models.TextField()),
                ('issue_type', models.TextField()),
                ('severity', models.TextField()),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dataruns.run')),
            ],
            options={
                'db_table': 'run_issues',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RunIssueImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_impact', models.DecimalField(decimal_places=6, max_digits=20)),
                ('risk_score', models.DecimalField(decimal_places=6, max_digits=20)),
                ('run_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='dataruns.runissue')),
            ],
            options={
                'db_table': 'run_issue_impact',
            },
        ),
        migrations.CreateModel(
            name='RunJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.TextField()),
                ('status', models.TextField()),
                ('priority', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('max_attempts', models.IntegerField()),
                ('queued_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='dataruns.run')),
            ],
            options={
                'db_table': 'run_jobs',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='RunSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cron', models.TextField()),
                ('timezone', models.TextField()),
                ('is_active', models.BooleanField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_schedules', to='tenants.company')),
            ],
            options={
                'db_table': 'run_schedules',
            },
        ),
        migrations.CreateModel(
            name='RunVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField()),
                ('verification_score', models.DecimalField(decimal_places=6, max_digits=20)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dataruns.run')),
            ],
            options={
                'db_table': 'run_verification',
            },
        ),
        migrations.CreateModel(
            name='RunScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.TextField()),
                ('entity_id', models.TextField()),
                ('score', models.DecimalField(decimal_places=6, max_digits=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dataruns.run')),
                ('scoring_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_scores', to='dataruns.scoringmodel')),
            ],
            options={
                'db_table': 'run_scores',
            },
        ),
    ]
