# Generated by Django 5.2.16 on 2026-07-25 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0004_contacts_orders_metrics_fk_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_id', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('weight_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dimension_masters',
                'ordering': ['dimension_id'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseTaxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'root_cause_taxonomies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CheckMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(unique=True)),
                ('check_id', models.CharField(max_length=8, unique=True)),
                ('check_name', models.CharField(max_length=255)),
                ('check_class', models.CharField(choices=[('RULE_BASED', 'Rule-based'), ('DRIFT', 'Drift')], max_length=32)),
                ('check_type', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('GATE', 'Gate'), ('SCORED', 'Scored')], max_length=16)),
                ('cadence', models.CharField(max_length=32)),
                ('phase', models.CharField(max_length=16)),
                ('systems_compared', models.TextField()),
                ('numeric_weight', models.PositiveSmallIntegerField(default=0)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='dataruns.dimensionmaster')),
                ('root_causes', models.ManyToManyField(blank=True, related_name='checks', to='dataruns.rootcausetaxonomy')),
            ],
            options={
                'db_table': 'check_masters',
                'ordering': ['sequence'],
            },
        ),
    ]
