# Generated by Django 5.2.16 on 2026-07-27 05:10

from django.db import migrations, models


def migrate_root_cause_ids(apps, schema_editor):
    CheckMaster = apps.get_model("dataruns", "CheckMaster")

    for check in CheckMaster.objects.all():
        codes = list(
            check.root_causes.order_by("code").values_list("code", flat=True)
        )
        check.root_cause_ids = codes
        check.save(update_fields=["root_cause_ids"])


class Migration(migrations.Migration):

    dependencies = [
        ("dataruns", "0005_dcs_master_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootcausetaxonomy",
            name="standard_remediation_pattern",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="purpose",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="percent_needed",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="result_status_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="confidence_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dimensionmaster",
            name="final_state_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="checkmaster",
            name="root_cause_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_root_cause_ids, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="checkmaster",
            name="root_causes",
        ),
        migrations.RenameModel(
            old_name="RootCauseTaxonomy",
            new_name="RootCauseMaster",
        ),
        migrations.AlterModelTable(
            name="rootcausemaster",
            table="root_cause_masters",
        ),
    ]
