# Generated by Django 5.2.16 on 2026-08-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0008_audit_log_governance'),
        ('dataruns', '0010_contact_link_key'),
    ]

    operations = [
    ]
