# Generated by Django 5.2.16 on 2026-08-07 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0014_checkmaster_fix_ownership'),
        ('tenants', '0007_normalize_connector_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('mode', models.CharField(blank=True, choices=[('AUGMENT', 'Augment'), ('SELECTIVE_REBUILD', 'Selective rebuild'), ('REBUILD', 'Rebuild'), ('INCOMPLETE', 'Incomplete')], max_length=32, null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('critical_defects', models.PositiveIntegerField(default=0)),
                ('evidence_coverage', models.DecimalField(blank=True, decimal_places=4, help_text='0-1 coverage fraction from pack sheet 06.', max_digits=5, null=True)),
                ('probe_coverage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_assessments', to='tenants.company')),
                ('data_run', models.OneToOneField(help_text='AF job DataRun (metadata.kind=architecture_assessment).', on_delete=django.db.models.deletion.CASCADE, related_name='architecture_assessment', to='dataruns.datarun')),
                ('source_dcs_data_run', models.ForeignKey(blank=True, help_text='DCS DataRun that triggered this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architecture_assessments_sourced', to='dataruns.datarun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_assessments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'architecture_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('WORKFLOW', 'Workflow'), ('SEGMENT', 'Segment'), ('TAG', 'Tag'), ('PROPERTY', 'Property'), ('SURFACE', 'Surface'), ('RECOMMENDATION', 'Recommendation'), ('CHANNEL', 'Channel'), ('METRIC', 'Metric')], max_length=32)),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('lifecycle_stage', models.CharField(blank=True, max_length=128, null=True)),
                ('capability_path', models.CharField(blank=True, default='', max_length=255)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dataruns.architectureassessment')),
            ],
            options={
                'db_table': 'architecture_assets',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureAssetVerdict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=255)),
                ('verdict', models.CharField(choices=[('KEEP', 'Keep'), ('KEEP_IMPROVE', 'Keep improve'), ('FIX_FIRST', 'Fix first'), ('CONSOLIDATE', 'Consolidate'), ('RETIRE_CANDIDATE', 'Retire candidate')], max_length=32)),
                ('evidence_ids', models.JSONField(blank=True, default=list)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('dcs_check_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_verdicts', to='dataruns.architectureassessment')),
            ],
            options={
                'db_table': 'architecture_asset_verdicts',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_asset_id', models.CharField(max_length=255)),
                ('target_asset_id', models.CharField(max_length=255)),
                ('edge_type', models.CharField(max_length=64)),
                ('rule_id', models.CharField(blank=True, default='', max_length=32)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='dataruns.architectureassessment')),
            ],
            options={
                'db_table': 'architecture_edges',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureProbeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probe_id', models.CharField(max_length=32)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe_results', to='dataruns.architectureassessment')),
            ],
            options={
                'db_table': 'architecture_probe_results',
            },
        ),
        migrations.AddIndex(
            model_name='architectureassessment',
            index=models.Index(fields=['company', '-created_at'], name='af_assess_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='architectureassessment',
            index=models.Index(fields=['company', 'status'], name='af_assess_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='architectureasset',
            index=models.Index(fields=['assessment', 'asset_type'], name='af_assets_assess_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='architectureasset',
            constraint=models.UniqueConstraint(fields=('assessment', 'asset_id'), name='uniq_af_assets_assessment_asset_id'),
        ),
        migrations.AddConstraint(
            model_name='architectureassetverdict',
            constraint=models.UniqueConstraint(fields=('assessment', 'asset_id'), name='uniq_af_verdicts_assessment_asset_id'),
        ),
        migrations.AddIndex(
            model_name='architectureedge',
            index=models.Index(fields=['assessment', 'source_asset_id'], name='af_edges_src_idx'),
        ),
        migrations.AddIndex(
            model_name='architectureedge',
            index=models.Index(fields=['assessment', 'target_asset_id'], name='af_edges_tgt_idx'),
        ),
        migrations.AddConstraint(
            model_name='architectureproberesult',
            constraint=models.UniqueConstraint(fields=('assessment', 'probe_id'), name='uniq_af_probes_assessment_probe_id'),
        ),
    ]
