# Generated by Django 5.2.16 on 2026-08-10 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0015_architecture_assessment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCasePilot',
            fields=[
                ('use_case_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('pilot_rank', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('release', models.CharField(default='MVP1', max_length=32)),
                ('manifest_status', models.CharField(blank=True, default='', max_length=64)),
                ('mcp_dependency', models.BooleanField(default=True)),
                ('fallback', models.CharField(blank=True, default='', max_length=128)),
                ('blueprint_file', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'use_case_pilots',
                'ordering': ['pilot_rank'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint_id', models.CharField(max_length=128, unique=True)),
                ('schema_version', models.CharField(max_length=32)),
                ('body', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.OneToOneField(db_column='use_case_id', on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='dataruns.usecasepilot')),
            ],
            options={
                'db_table': 'use_case_blueprints',
                'ordering': ['pilot__pilot_rank'],
            },
        ),
        migrations.CreateModel(
            name='PilotStageMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=32)),
                ('is_primary', models.BooleanField(default=True)),
                ('pilot', models.ForeignKey(db_column='use_case_id', on_delete=django.db.models.deletion.CASCADE, related_name='stage_maps', to='dataruns.usecasepilot')),
            ],
            options={
                'db_table': 'pilot_stage_maps',
                'ordering': ['pilot__pilot_rank', 'stage_id'],
                'constraints': [models.UniqueConstraint(fields=('pilot', 'stage_id'), name='pilot_stage_map_unique')],
            },
        ),
    ]
