# Generated by Django 5.2.16 on 2026-08-11 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0016_use_case_pilot_models'),
        ('tenants', '0007_normalize_connector_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritebackJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_id', models.CharField(max_length=16)),
                ('mode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('diff_hash', models.CharField(max_length=64)),
                ('approval_tier', models.CharField(blank=True, default='', max_length=20)),
                ('approval_id', models.UUIDField(blank=True, null=True)),
                ('token_binds', models.JSONField(blank=True, default=dict)),
                ('intents', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('sandbox', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeback_jobs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeback_jobs', to='tenants.company')),
            ],
            options={
                'db_table': 'writeback_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='writeback_j_company_7619fc_idx'), models.Index(fields=['company', 'check_id', '-created_at'], name='writeback_j_company_3b5efb_idx')],
            },
        ),
    ]
