# Generated by Django 5.2.16 on 2026-08-13 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0019_assessment_report'),
        ('tenants', '0007_normalize_connector_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=64)),
                ('check_id', models.CharField(blank=True, default='', max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('policy_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=64)),
                ('langsmith_run_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('gate_denied', 'Gate denied')], max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=64)),
                ('check_id', models.CharField(blank=True, default='', max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('headline', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_suggestions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='assessmentreport',
            new_name='assessment__company_89eee8_idx',
            old_name='assessment__company_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='writebackapprovaltoken',
            new_name='writeback_a_company_3f283a_idx',
            old_name='writeback_a_company_0f0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='writebackapprovaltoken',
            new_name='writeback_a_diff_ha_fa4acc_idx',
            old_name='writeback_a_diff_ha_1a1a1a_idx',
        ),
        migrations.AlterField(
            model_name='writebackapprovaltoken',
            name='issued_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='aicall',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='aicall',
            name='dcs_data_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to='dataruns.datarun'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='ai_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='dataruns.aicall'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='dcs_data_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='dataruns.datarun'),
        ),
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['company', '-created_at'], name='ai_calls_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['company', 'task_type'], name='ai_calls_company_task_idx'),
        ),
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['fingerprint'], name='ai_calls_fingerprint_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['company', 'task_type', 'check_id'], name='ai_sugg_company_task_check_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['fingerprint'], name='ai_sugg_fingerprint_idx'),
        ),
        migrations.AddConstraint(
            model_name='aisuggestion',
            constraint=models.UniqueConstraint(fields=('company', 'task_type', 'fingerprint'), name='uniq_ai_suggestions_company_task_fp'),
        ),
    ]
