# Generated by Django 5.2.16 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0020_ai_call_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='error_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='aicall',
            name='langsmith_run_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
