# Generated by Django 5.2.16 on 2026-08-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataruns', '0023_workflow_build_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowbuildpackage',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_packages', to='dataruns.usecasepilot'),
        ),
    ]
