# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataruns", "0032_orchestrationtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisuggestion",
            name="content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(
                fields=["company", "task_type", "check_id", "content_hash"],
                name="ai_sugg_content_hash_idx",
            ),
        ),
    ]
